---
- name: Check Ports
  hosts: win_iis
  gather_facts:  false

  tasks:
  - name: Check if port 80 (HTTP) is open
    ansible.windows.win_wait_for:
      port: 80
      timeout: 30
    register: port_check

  - name: Show Output
    debug:
      var: port_check