---
- name: Check Ports
  hosts: all
  gather_facts:  false
  #vars:
  #  port_num: 80

  tasks:
  - name: "Check if port {{ port_num }} is open"
    ansible.windows.win_wait_for:
      port: "{{ port_num }}"
      timeout: 30
    register: port_check

  - name: Show Output
    debug:
      var: port_check