---
- name: Check and Restart Windows Services
  hosts: all
  gather_facts: false
  #vars:
    #services_to_check:
    #- W3SVC # IIS service name

  tasks:
  - name: Check Services Status
    ansible.windows.win_service_info:
      name: "{{ item }}"
    register: service_results
    loop: "{{ services_to_check }}"

  - name: Set variable
    set_fact:
      output: "{{ service_results.results[0].services[0] }}"

  - name: Services status
    fail:
      msg: "{{ output.name }} , {{ output.display_name}} is {{ output.state }}"
    when: output.state != 'started'
 
  - name: Services status
    debug:
      msg: "{{ output.name }} , {{ output.display_name}} is {{ output.state }}"
    when: output.state == 'started'