---
- name: Get AD Object Info
  hosts: all # Target your domain controller
  gather_facts: false
  #vars:
    #dn_path: cn=pam,ou=Server,ou=IT,DC=mydomain,DC=local

  tasks:
  - name: Get all properties for the user using its DistinguishedName
    microsoft.ad.object_info:
      identity: "{{ dn_path }}"
      properties: '*'
    register: output

  - name: Show output
    debug:
      var: output

