---
- name: Modify grops for AD user
  hosts: win_ad  # Target your domain controller
  gather_facts: false
  #vars:
    #username: 
    #dn_path: ou=Managers,ou=Sales,DC=mydomain,DC=local
 
  tasks:
  - name: Get all properties for the user using its DistinguishedName
    microsoft.ad.object_info:
      identity: "cn={{ username }},{{ dn_path }}"
      properties: '*'
    register: output

  - name: Show current membership
    debug:
      msg: " {{ username }} is curreently a member of {{output.objects[0].memberOf}}"
