---
- name: Install IIS
  hosts: "{{ HOSTS }}"
#  vars:
#    source:

  tasks:
    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present

    - name: Start IIS service
      win_service:
        name: W3Svc
        state: started

    - name: Create website index.html
      win_copy:
        src: "{{ source }}"
        dest: C:\Inetpub\wwwroot\

    - name: Show website address
      debug:
        msg: http://{{ ansible_host }}