---
- name: Install IIS
  hosts: "{{ HOSTS | default('windows') }}"
  vars:
#    ftp_user: 
#    ftp_pass:
    source: /tmp/static-website-example-master.tar.gz
    s_folder: /tmp/static-website-example-master/

  tasks:
    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present

    - name: Start IIS service
      win_service:
        name: W3Svc
        state: started

    - name: Download file from FTP with authentication
      ansible.builtin.get_url:
        url: ftp://{{ftp_user}}:{{ftp_pass}}@files.000webhost.com/public_html/static-website-example-master.tar.gz
        dest: "{{ source }}"
      delegate_to: localhost

    - name: Extract zip
      ansible.builtin.unarchive:
        src: "{{ source }}"
        dest: /tmp
      delegate_to: localhost
         
    - name: Create website index.html
      win_copy:
        src: "{{ s_folder }}"
        dest: C:\Inetpub\wwwroot\

    - name: Show website address
      debug:
        msg: http://{{ ansible_host }}