---
- name: Check for updates and email the patches list
  hosts: all
  gather_facts: False
  tasks:
  - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
    ansible.windows.win_updates:
      category_names: 
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      state: searched
      log_path: C:\ansible_wu.txt
  - name: Copy patch list
    ansible.builtin.fetch:
      src: C:\ansible_wu.txt
      dest: /tmp/win_patches.log
      flat: true
  - name: email to admin
    mail:
      host: smtp-relay.sendinblue.com
      port: 587
      username: "{{outlook_user}}"
      password: "{{outlook_pass}}"
      from: admin_ansible@example.com
      to: "{{email}}"
      subject: Windows patch report
      body: "The list of required Windows Update for the Windows VMs can be found in the attached file"
      attach:
      - /tmp/win_patches.log
    delegate_to: localhost
    