- name: Create Azure Webapp for TODO Application
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    resource_group: openenv-vghwm
    vm_name: demo85
    rnum: 85

  tasks:

    - name: Obtain Azure Container Registry Facts
      azure_rm_containerregistry_info:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}{{ rnum }}acr"
        retrieve_credentials: true
      register: acr_output

    - name: Obtain Cosmos DB Facts
      azure_rm_cosmosdbaccount_info:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-cosmosdb"
        retrieve_keys: all
        retrieve_connection_strings: yes
      register: cosmos_output
