---
- name: Configure ACMECorp Jenkins job
  hosts: controller.acme.example.com
  gather_facts: false

  tasks:
  - name: Create a jenkins job using basic authentication
    environment:
      PYTHONHTTPSVERIFY: 0
    community.general.jenkins_job:
      config: "{{ lookup('file', 'acme.xml') }}"
      name: ACMECorp
      user: "{{ student_user }}"
      password: "{{ student_password }}"
      url: "{{ ciserver_url }}"
      validate_certs: false
