- hosts: localhost
  connection: local
  tasks:
    - name: Delete App Service
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp_name }}"
        state: absent